version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./fixtures.json:/app/fixtures.json
      - ./kb.json:/app/kb.json
    restart: unless-stopped

  bot:
    build: .
    command: python bot.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
