# Railway configuration
[build]
builder = "dockerfile"
path = "backend"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8000"
